/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSelectCodeRouteImport } from './routes/team-select.$code'
import { Route as ResultCodeRouteImport } from './routes/result.$code'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as BattleCodeRouteImport } from './routes/battle.$code'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSelectCodeRoute = TeamSelectCodeRouteImport.update({
  id: '/team-select/$code',
  path: '/team-select/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultCodeRoute = ResultCodeRouteImport.update({
  id: '/result/$code',
  path: '/result/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleCodeRoute = BattleCodeRouteImport.update({
  id: '/battle/$code',
  path: '/battle/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/result/$code': typeof ResultCodeRoute
  '/team-select/$code': typeof TeamSelectCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/result/$code': typeof ResultCodeRoute
  '/team-select/$code': typeof TeamSelectCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/shop': typeof ShopRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/result/$code': typeof ResultCodeRoute
  '/team-select/$code': typeof TeamSelectCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/shop'
    | '/battle/$code'
    | '/lobby/$code'
    | '/result/$code'
    | '/team-select/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/shop'
    | '/battle/$code'
    | '/lobby/$code'
    | '/result/$code'
    | '/team-select/$code'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/shop'
    | '/battle/$code'
    | '/lobby/$code'
    | '/result/$code'
    | '/team-select/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ShopRoute: typeof ShopRoute
  BattleCodeRoute: typeof BattleCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  ResultCodeRoute: typeof ResultCodeRoute
  TeamSelectCodeRoute: typeof TeamSelectCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-select/$code': {
      id: '/team-select/$code'
      path: '/team-select/$code'
      fullPath: '/team-select/$code'
      preLoaderRoute: typeof TeamSelectCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$code': {
      id: '/result/$code'
      path: '/result/$code'
      fullPath: '/result/$code'
      preLoaderRoute: typeof ResultCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$code': {
      id: '/battle/$code'
      path: '/battle/$code'
      fullPath: '/battle/$code'
      preLoaderRoute: typeof BattleCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ShopRoute: ShopRoute,
  BattleCodeRoute: BattleCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  ResultCodeRoute: ResultCodeRoute,
  TeamSelectCodeRoute: TeamSelectCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
